### ISSUE TITLE
BadMethodCallException  Call to undefined method GeneaLabs\LaravelModelCaching\CachedBuilder::groupLimit().

### ISSUE THREAD

**Issue by loveshiun** [staudenmeir/eloquent-eager-limit-x-laravel-adjacency-list#2]
Error `BadMethodCallException  Call to undefined method GeneaLabs\LaravelModelCaching\CachedBuilder::groupLimit().` occurred when using eager limit.

packages

- genealabs/laravel-model-caching                           11.0.1
- 
- staudenmeir/eloquent-eager-limit                          v1.8.3
- staudenmeir/eloquent-eager-limit-x-laravel-adjacency-list v1.2
- staudenmeir/eloquent-eager-limit-x-laravel-cte            v1.1.1
- staudenmeir/eloquent-has-many-deep-contracts              v1.1
- staudenmeir/laravel-adjacency-list                        v1.20.1
- staudenmeir/laravel-cte                                   v1.10

***

```php
class Node extends Model
{
    use \GeneaLabs\LaravelModelCaching\Traits\Cachable;
    use \Staudenmeir\EloquentEagerLimitXLaravelAdjacencyList\Eloquent\HasEagerLimitAndGraphRelationships;

    public function names() {
        return $this->morphMany(Name::class, "morphname");
    }

    public function simpleNames() {
        return $this->hasMany(SimpleNames::class);
    }

    public function hasRecursiveRelationshipsNames() {
        // the HasRecursiveRelationshipsNames class includes `use Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;`
        return $this->hasMany(HasRecursiveRelationshipsNames::class);
    }
}
```

```php
$relationship = "names"; // or "simpleNames", "hasRecursiveRelationshipsNames", ...
Node::with([$relationship => function($query) {
    $query->limit(1);
}])->where("id", "<", 10)->get();
```

Some relations seem to be working correctly, while others have errors.

```
BadMethodCallException  Call to undefined method Staudenmeir\LaravelAdjacencyList\Eloquent\Builder::groupLimit().
```

```
BadMethodCallException  Call to undefined method GeneaLabs\LaravelModelCaching\CachedBuilder::groupLimit().
```

Is this related to the mentioned [Limitations](https://github.com/staudenmeir/eloquent-eager-limit-x-laravel-adjacency-list?tab=readme-ov-file#limitations-1), or is it just not directly compatible with other packages (laravel-model-caching)?

**Comment by staudenmeir** [comment]
Hi @loveshiun,

> $relationship = "names"; // or "simpleNames", "hasRecursiveRelationshipsNames", ...

> Some relations seem to be working correctly, while others have errors.

Which relationships are working and which aren't?

**Comment by loveshiun** [comment]
- `simpleNames()`:

    using `hasMany()`

    no Exception

- `hasRecursiveRelationshipsNames()`: 

    `hasMany()`, the relation uses other trait, like: `HasRecursiveRelationships`

    Exception

    ```
    BadMethodCallException  Call to undefined method Staudenmeir\LaravelAdjacencyList\Eloquent\Builder::groupLimit().
    ```

- `names()`: 

    uses `morphMany()`, but package <https://packagist.org/packages/genealabs/laravel-model-caching> is used. I included this in the test, because many models of my current project uses it. I deem it as a built-in feature or a candidate when I need to select one from multiple packages.

    Exception

    ```
    BadMethodCallException  Call to undefined method GeneaLabs\LaravelModelCaching\CachedBuilder::groupLimit().
    ```

    If I do not include the model caching package, it causes other errors: 

    ```
    BadMethodCallException  Call to undefined method Illuminate\Database\Eloquent\Builder::groupLimit().
    ```

**Comment by staudenmeir** [comment]
The related models also need to use the `HasEagerLimit` trait. In the case of `HasRecursiveRelationshipsNames`, replace the `HasRecursiveRelationships` trait with `HasEagerLimitAndRecursiveRelationships`.

**Comment by loveshiun** [comment]
Resolved after using `HasEagerLimitAndRecursiveRelationships` in related models.

Thank you.
